### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by djoudi** [nbphpcouncil/nb-laravel-plugin#1]
how to install in netbeans?

**Comment by junichi11** [comment]
@jtakakura 
I think that we should create tags. If so, we can provide nbms for each tags.
If you are OK with me, I'll do that :)

Thanks.

**Comment by junichi11** [comment]
Please download the following:

https://github.com/nbphpcouncil/nb-laravel-plugin/releases/tag/v0.1.1

#### Note

This works in only NB74. Perhaps, we have to update NB before we install this nbm.
