### ISSUE TITLE
Error when installing though netbeans

### ISSUE THREAD

**Issue by dragonfire1119** [nbphpcouncil/nb-laravel-plugin#2]
Some plugins require plugin PHP Executable API to be installed.
The plugin PHP Executable API is requested in implementation version 201302132200.  The following plugin is affected:       Laravel4 Framework 
Some plugins require plugin PHP Framework API to be installed.
The plugin PHP Framework API is requested in implementation version 201302132200.  The following plugin is affected:       Laravel4 Framework 
Some plugins require plugin PHP Module API to be installed.
The plugin PHP Module API is requested in implementation version 201302132200.  The following plugin is affected:       Laravel4 Framework 
Some plugins require plugin Composer to be installed.
The plugin Composer is requested in implementation version 201302132200.  The following plugin is affected:       Laravel4 Framework  Some plugins not installed to avoid potential installation problems.

You can't press next either.

**Comment by junichi11** [comment]
Hi,

Sorry, this plugin depends on NB build version. 
What is your NB version?

Perhaps, Nbms will be provided for each version on Plugin Portal or here later.

Thanks.

**Comment by dragonfire1119** [comment]
My version is the newest 7.4. Your description says 7.4+ so I would think it would work?

Thanks for the reply.

**Comment by junichi11** [comment]
Where did you get your nbm?
If it's java.net, maybe it's for NB7.3. As I wrote the above, unfortunately, this plugin depends on version number of NetBeans. So, you got error messages.

Thanks.

**Comment by dragonfire1119** [comment]
https://netbeans.org/downloads/ is where I got it and the HTML5 & PHP I didn't get it from java.net. My nbm is NetBeans IDE 7.4 (Build 201310111528) so it's not 7.3.

Thanks @junichi11 for the support.

**Comment by junichi11** [comment]
I see. I guess that you created a nbm with 7.3 once.
Please try to clean and rebuild.

Could you tell me your steps?
We can't understand your state (got it? or created it?) if there is no concrete information(e.g. what did you, steps).

I confirmed that it can install with NetBeans 7.4. (I created a nbm with NB7.4)

#### my environment

Product Version: NetBeans IDE 7.4 (Build 201310111528)
Java: 1.7.0_45; Java HotSpot(TM) Client VM 24.45-b08
Runtime: Java(TM) SE Runtime Environment 1.7.0_45-b18
System: Linux version 3.2.0-56-generic-pae running on i386; UTF-8; 

HTH,
Junichi

**Comment by dragonfire1119** [comment]
## Steps
1. I completely uninstalled the netbeans 7.4.
2. Went to netbeans.org and downloaded a new installation.
3. Installed 7.4
4. Went to Tools | Plugins | Settings
5. Found this on google https://java.net/projects/nb-laravel-plugin/pages/Home for the plugin repository.
6. Tried to install it again and got the same errors

## Errors

Some plugins require plugin PHP Executable API to be installed.
The plugin PHP Executable API is requested in implementation version 201302132200.  The following plugin is affected:       Laravel4 Framework 
Some plugins require plugin PHP Framework API to be installed.
The plugin PHP Framework API is requested in implementation version 201302132200.  The following plugin is affected:       Laravel4 Framework 
Some plugins require plugin PHP Module API to be installed.
The plugin PHP Module API is requested in implementation version 201302132200.  The following plugin is affected:       Laravel4 Framework 
Some plugins require plugin Composer to be installed.
The plugin Composer is requested in implementation version 201302132200.  The following plugin is affected:       Laravel4 Framework  Some plugins not installed to avoid potential installation problems.

## My environment

Product Version: NetBeans IDE 7.4 (Build 201310111528)
Java: 1.7.0_21; Java HotSpot(TM) 64-Bit Server VM 23.21-b01
Runtime: Java(TM) SE Runtime Environment 1.7.0_21-b12
System: Mac OS X version 10.9 running on x86_64; UTF-8; en_US (nb)

Hope this helps you in solving this major bug.

**Comment by junichi11** [comment]
Thanks for your detail steps :) I see now.

> Found this on google https://java.net/projects/nb-laravel-plugin/pages/Home for the plugin repository.

This means https://github.com/nbphpcouncil/nb-laravel-plugin/issues/2#issuecomment-28146053 (I said java.net)
i.e. It's for **7.3**. This is not a bug.

I think that new nbm will be provided for NB7.4 soon. So, please wait a while.

Thanks.

**Comment by dragonfire1119** [comment]
Oh ok I see the java.net my mistake. Then do you have a different url to put in since you were able to install the plugin on 7.4?

Thanks

**Comment by junichi11** [comment]
> Then do you have a different url to put in since you were able to install the plugin on 7.4?

No, I don't. I just created a new nbm. It may cause confusion that I provide a url or nbm arbitrarily. I have asked member(author) to provide a nbm in issue 1. I'm not sure whether new url is provided. It might be provided it by author on java.net.

Thanks.

**Comment by xhava** [comment]
hi how can i install this plugin for netbeans 7.4 i have the same errors 

Some plugins require plugin PHP Framework API to be installed.
The plugin PHP Framework API is requested in implementation version 201302132200.  The following plugin is affected:       Laravel4 Framework 
Some plugins require plugin PHP Module API to be installed.
The plugin PHP Module API is requested in implementation version 201302132200.  The following plugin is affected:       Laravel4 Framework 
Some plugins require plugin Composer to be installed.
The plugin Composer is requested in implementation version 201302132200.  The following plugin is affected:       Laravel4 Framework  Some plugins not installed to avoid potential installation problems.

**Comment by eviweb** [comment]
Hi,

to make it work on my netbeans 7.4, I've cloned this repo, rebuilt the npm and installed it manually.

Eric

**Comment by xhava** [comment]
hi @eviweb a lot of thanks for answering but  i really have not idea how to do that. please some usefull link to get this done.

**Comment by junichi11** [comment]
I have added a new nbm.
Please download the following:

https://github.com/nbphpcouncil/nb-laravel-plugin/releases/tag/v0.1.1

#### Note

This works in only NB74. Perhaps, we have to update NB before we install this nbm.

**Comment by xhava** [comment]
thanks @junichi11

**Comment by xhava** [comment]
hi again  @junichi11  do u know where i can find the plugin composer because it is required for installing laravel plugin

**Comment by junichi11** [comment]
Hi @xhava ,

Have a look at `Tools > Options > PHP > Composer`

**Comment by xhava** [comment]
yes composer is there. C:\ProgramData\Composer\bin\composer

**Comment by xhava** [comment]
but witch could be the error

**Comment by junichi11** [comment]
> yes composer is there. C:\ProgramData\Composer\bin\composer

Sorry, I'm not sure  exactly what you would like to do.
Did you get error messages?

Could you tell me the your steps? If it's a bug, please submit it as a new issue.

**Comment by xhava** [comment]
1.- download https://github.com/nbphpcouncil/nb-laravel-plugin/releases/tag/v0.1.1
2.- tools > plugins ->downloaded >add plugins  and i selected the plugin laravel then i click on install

and this is the error  -> Some plugins require plugin Composer to be installed ,
                                   the plugin Composer is requested in implementation version 201311191022.
                                    The following plugin is affected:       Laravel4 Framework

**Comment by papajoker** [comment]
same error "The plugin Composer is requested in implementation version 201311191022."
and i have plugin installed : `Composer 0.13.2`

`Product Version: NetBeans IDE 7.4 (Build 201310111528)
Updates: NetBeans IDE is updated to version NetBeans 7.4 Patch 2
Java: 1.7.0_45; OpenJDK 64-Bit Server VM 24.45-b08
Runtime: OpenJDK Runtime Environment 1.7.0_45-b3
System: Linux version 3.12.3-1-MANJARO running on amd64; UTF-8; fr_FR (nb)`

**Comment by junichi11** [comment]
Thanks for your answer. I see now.
Did you update NetBeans? Some patched was released.

my environment:
Product Version: NetBeans IDE 7.4 (Build 201310111528)
Java: 1.7.0_45; Java HotSpot(TM) Client VM 24.45-b08
Runtime: Java(TM) SE Runtime Environment 1.7.0_45-b18
System: Linux version 3.2.0-57-generic-pae running on i386;

Could you show your environment?

**Comment by xhava** [comment]
my environment : 
Product Version: NetBeans IDE 7.4 (Build 201310111528)
Updates: NetBeans IDE is updated to version NetBeans 7.4 Patch 2
Java: 1.7.0_17; Java HotSpot(TM) 64-Bit Server VM 23.7-b01
Runtime: Java(TM) SE Runtime Environment 1.7.0_17-b02
System: Windows 7 version 6.1 running on amd64; Cp1252; es_MX (nb)

**Comment by junichi11** [comment]
I rebuilt it. Please try to install it.

I'll also try to install in another environment.

Thanks.

**Comment by xhava** [comment]
nop . unsuccessfully ;( i''ll also try to install in another environment too

**Comment by junichi11** [comment]
I was able to install the plugin in windows. (with patch2)
1. update nb
2. download nbm from this site
3. install plugin

Product Version: NetBeans IDE 7.4 (Build 201310111528)
Java: 1.7.0_40; Java HotSpot(TM) 64-Bit Server VM 24.0-b56
Runtime: Java(TM) SE Runtime Environment 1.7.0_40-b43
System: Windows 7 version 6.1 running on amd64; MS932; 

Umm, I'm not sure the cause yet...
Perhaps, I think that version number of Java doesn't relate to this. But you should update it :)

Please try to confirm updates again (Help > Check for Updates)

**Comment by xhava** [comment]
Thanks.  I will update.java.

--- Mensaje Original ---

Desde: "junichi11" notifications@github.com
Enviado: 17 de diciembre de 2013 21:10
Para: "nbphpcouncil/nb-laravel-plugin" nb-laravel-plugin@noreply.github.com
Cc: "chrystopher salvador" salvador89_1@hotmail.com
Asunto: Re: [nb-laravel-plugin] Error when installing though netbeans (#2)

I was able to install the plugin in windows. (with patch2)
1. update nb
2. download nbm from this site
3. install plugin

Product Version: NetBeans IDE 7.4 (Build 201310111528)
Java: 1.7.0_40; Java HotSpot(TM) 64-Bit Server VM 24.0-b56
Runtime: Java(TM) SE Runtime Environment 1.7.0_40-b43
System: Windows 7 version 6.1 running on amd64; MS932;

Umm, I'm not sure the cause yet...
Perhaps, I think that version number of Java doesn't relate to this. But you should update it :)

---

**Comment by xhava** [comment]
hi @junichi11 this is my new environment and it still not works ..

Product Version: NetBeans IDE 7.4 (Build 201310111528)
Updates: NetBeans IDE is updated to version NetBeans 7.4 Patch 2
Java: 1.7.0_45; Java HotSpot(TM) 64-Bit Server VM 24.45-b08
Runtime: Java(TM) SE Runtime Environment 1.7.0_45-b18
System: Windows 8 version 6.2 running on amd64; Cp1252; es_MX (nb)
User directory: C:\Users\chrystopher\AppData\Roaming\NetBeans\7.4
Cache directory: C:\Users\chrystopher\AppData\Local\NetBeans\Cache\7.4

this is my error 
Some plugins require plugin Composer to be installed.
The plugin Composer is requested in implementation version 201311191022.  The following plugin is affected:       Laravel4 Framework

**Comment by xhava** [comment]
i tried on linux but nothing happens.

**Comment by xhava** [comment]
but i can do this composer install on my php project . so what will be wrong

**Comment by junichi11** [comment]
Perhaps, I think that you have not updated NetBeans yet.
Did you update (Menu : Help > Check for Updates) after you install NB?

**Comment by xhava** [comment]
Ye.and netbeans says me that.there is nit updates avalaible

--- Mensaje Original ---

Desde: "junichi11" notifications@github.com
Enviado: 20 de diciembre de 2013 17:29
Para: "nbphpcouncil/nb-laravel-plugin" nb-laravel-plugin@noreply.github.com
Cc: "chrystopher salvador" salvador89_1@hotmail.com
Asunto: Re: [nb-laravel-plugin] Error when installing though netbeans (#2)

Perhaps, I think that you have not updated NetBeans yet.
Did you update (Menu : Help > Check for Updates) after you install NB?

---

**Comment by junichi11** [comment]
Umm, I'm not sure the cause yet.
Can you check the following?

META-INF/MANIFEST.MF file in path/to/NetBeans7.4/php/modules/org-netbeans-modules-php-composer-jar

If possible, you will find a line like this OpenIDE-Module-Implementation-Version: 201311191022

If there is difference of this version number, we can not install the plugin because this plugin depends on the this version number.

**Comment by xhava** [comment]
Tjanks i.will check it just right now

--- Mensaje Original ---

Desde: "junichi11" notifications@github.com
Enviado: 20 de diciembre de 2013 19:42
Para: "nbphpcouncil/nb-laravel-plugin" nb-laravel-plugin@noreply.github.com
Cc: "chrystopher salvador" salvador89_1@hotmail.com
Asunto: Re: [nb-laravel-plugin] Error when installing though netbeans (#2)

Umm, I'm not sure the cause yet.
Can you check the following?

META-INF/MANIFEST.MF file in path/to/NetBeans7.4/php/modules/org-netbeans-modules-php-composer-jar

If possible, you will find a line like this OpenIDE-Module-Implementation-Version: 201311191022

If there is difference of this version number, we can not install the plugin because this plugin depends on the this version number.

---

**Comment by bryansiegel** [comment]
@junichi11 I get the error message The plugin Composer is requested in implementation version 201311191022.  I just downloaded the latest version of netbeans 7.4 and did all the steps above. My MANIFEST.MF  file says OpenIDE-Module-Implementation-Version: 201312091611. Does that mean that the laravel 4 plugin is running off an old version of composer that's bundled with Netbeans 7.4 ? Just in case here's my environment

Product Version: NetBeans IDE 7.4 (Build 201310111528)
Updates: NetBeans IDE is updated to version NetBeans 7.4 Patch 2
Java: 1.7.0_45; Java HotSpot(TM) 64-Bit Server VM 24.45-b08
Runtime: Java(TM) SE Runtime Environment 1.7.0_45-b18

Any ideas on how I can get this to work?

**Comment by autobitacora** [comment]
Same error message as bryansiegel 
Plugin Composer is instaled and in Version: 0.13.2
My environment:
Product Version: NetBeans IDE 7.4 (Build 201310111528)
Updates: NetBeans IDE is updated to version NetBeans 7.4 Patch 2
Java: 1.7.0_45; Java HotSpot(TM) 64-Bit Server VM 24.45-b08
Runtime: Java(TM) SE Runtime Environment 1.7.0_45-b18
System: Linux version 3.2.0-23-generic running on amd64; UTF-8; es_ES (nb)

**Comment by junichi11** [comment]
@bryansiegel 

> My MANIFEST.MF file says OpenIDE-Module-Implementation-Version: 201312091611.

The cause is this. I have downloaded NetBeans7.4 zip version. I'll create a new nbm with this version soon. Please wait a while.

Thanks.

**Comment by junichi11** [comment]
I've added a new nbm (org-nbphpcouncil-modules-php-laravel4-0.1.1-for-nb74-201312091611.nbm).

Please check it.

Thanks.

**Comment by bryansiegel** [comment]
@junichi11 thx. It works!. I have installed the plugin on netbeans 7.4 with your new plugin.

**Comment by xhava** [comment]
Hi could you tell me ur steps because i have not had success thanks

--- Mensaje Original ---

Desde: "Bryan Siegel" notifications@github.com
Enviado: 5 de enero de 2014 23:34
Para: "nbphpcouncil/nb-laravel-plugin" nb-laravel-plugin@noreply.github.com
Cc: "chrystopher salvador" salvador89_1@hotmail.com
Asunto: Re: [nb-laravel-plugin] Error when installing though netbeans (#2)

@junichi11 thx. It works!. I have installed the plugin on netbeans 7.4 with your new plugin.

---

**Comment by junichi11** [comment]
@xhava Did you try to install the new nbm? https://github.com/nbphpcouncil/nb-laravel-plugin/releases

**Comment by bryansiegel** [comment]
@xhava download and install the new plugin that @junichi11  compiled https://github.com/nbphpcouncil/nb-laravel-plugin/releases/tag/v0.1.1 it's the first one on the list. @xhava that's what worked for me. @xhava it's kinda bare bones at the moment. It doesn't have blade syntax highlighting which is a no go for me. But I do appreciate the effort and I know it's still the early stages.

**Comment by sufi7** [comment]
@junichi11 thanks a lot for the installing steps, please let me know the steps to do after installation of plugin (i.e, how to use it) links..

**Comment by junichi11** [comment]
@sufi7 Unfortunately, I'm not this plugin's author. Author is @jtakakura . AFAIK, there are the following features,
- Show badge icon
- New Project Wizard
- Create a file for auto code completion when we create a new project with New Project Wizard.

If you have some requests, please submit them as new issues.

Thanks.

**Comment by Purus** [comment]
I was getting the same composer error and I fixed it by adding the .phar extension to the composer path in Tools-> PHP->Composer tab.

Hope it helps someone.

**Comment by mohammad6006** [comment]
i install this and set composer 

but how can i use laravel?

there arent laravel in new projects

**Comment by junichi11** [comment]
@mohammad6006 
You should submit that as a new issue because it doesn't seem to relate to this issue ;)

**Comment by ananddpatil** [comment]
@Purus adding the .phar extension solved the problem for me. Thanks.
@junichi11 Cheers for the pointing to updated nbm

My Environment
org-nbphpcouncil-modules-php-laravel4-0.1.1-for-nb74-201312091611.nbm
on NetBeans IDE 7.4 (Build 201310111528)
Win7

**Comment by alastairparagas** [comment]
Is this plugin compatible with Netbeans 8.0? I get these errors when trying to install the plugin.

**Comment by junichi11** [comment]
@alastairparagas 

Please submit that as a new issue with your detail information (your nb version, plugin version, error messages, e.t.c)

Thanks.
