### ISSUE TITLE
Request to add this module to API friends

### ISSUE THREAD

**Issue by junichi11** [nbphpcouncil/nb-laravel-plugin#3]
Sorry, I have not finished this yet because new feature phase had already finished when this plugin was created.

**Comment by Monomachus** [comment]
Hmm, may be we could somehow improve this process. I'm thinking that may be PHP guys could create somehow a service which would have all the API friends. Via this service they could add or delete API friends at any time. 
Now it could have multiple flows:
- in the install itself NetBeans would have the default list of items that are available at the time of install.
- whenether a new plugin is installed, NB make a call to their service to check for new items.
  And that is how the newly created plugins don't wait in queue for being enabled, what do you think of this approach?
  Do you think it is doable?

**Comment by junichi11** [comment]
> in the install itself NetBeans would have the default list of items that are available at the time of install.
> whenether a new plugin is installed, NB make a call to their service to check for new items. And that is how the newly created plugins don't wait in queue for being enabled, 

Sorry, I'm not sure what this means yet exactly. 
Does this mean that we can use all php apis automatically without requests for PHP api friends?
IMHO, perhaps, I think that plugins can not be added to api friend dynamically because its list is hard-coded.

**Comment by Monomachus** [comment]
> IMHO, perhaps, I think that plugins can not be added to api friend dynamically because its list is hard-coded.

Yes this it the way things work now.
So I'll draw a little diagram to make it more explicit. And attach it here.

**Comment by junichi11** [comment]
OK :+1:

**Comment by junichi11** [comment]
I sent a request because new feature phase might finish.

This module was added.
http://hg.netbeans.org/web-main/rev/75e1e427c5a8

**Comment by Monomachus** [comment]
![nb_api_friends](https://f.cloud.github.com/assets/65164/1682687/90faeb00-5daf-11e3-93dc-ee88a3f7fed1.png)

Here is what I meant. I hope it is clearer now, let me know if you think it is a good idea.

**Comment by junichi11** [comment]
IMHO, api friends is hard-corded and built. Perhaps, it can't change later. So, I think that it can not add dynamically. (Of course, it would be great if it is possible to add dynamically.) But please try to ask NB PHP team that once if you think that it is possible because they know that whether it's possible.

Thank you.
