### ISSUE TITLE
plug in dependencies missing

### ISSUE THREAD

**Issue by belial-seed** [nbphpcouncil/nb-laravel-plugin#4]
hey, I found the link for the instalation in the java.net site, however when i try to install the plug in this message shows up:

Some plugins require plugin PHP Executable API to be installed.
The plugin PHP Executable API is requested in implementation version 201302132200. 

The following plugin is affected:
       Laravel4 Framework 
Some plugins require plugin PHP Framework API to be installed.
The plugin PHP Framework API is requested in implementation version 201302132200.
  The following plugin is affected:
       Laravel4 Framework 

Some plugins require plugin PHP Module API to be installed.
The plugin PHP Module API is requested in implementation version 201302132200.
  The following plugin is affected:
       Laravel4 Framework 
Some plugins require plugin Composer to be installed.
The plugin Composer is requested in implementation version 201302132200.
  The following plugin is affected:       Laravel4 Framework
  Some plugins not installed to avoid potential installation problems.
# 

Netbeans  specs are:
Product Version: NetBeans IDE 7.4 (Build 201310111528)
Updates: NetBeans IDE is updated to version NetBeans 7.4 Patch 2
Java: 1.7.0_45; Java HotSpot(TM) 64-Bit Server VM 24.45-b08
Runtime: Java(TM) SE Runtime Environment 1.7.0_45-b18
System: Windows 7 version 6.1 running on amd64; Cp1252; es_MX (nb)

thanks in advance

**Comment by junichi11** [comment]
Hi,

It's for NetBeans 7.3

Please try to install the following:
https://github.com/nbphpcouncil/nb-laravel-plugin/releases

Thanks.

**Comment by adem82** [comment]
I use nb 8.0 and got the following errors as i installed the plugings for laravel:

Some plugins require plugin PHP Executable API to be installed.
The plugin PHP Executable API is requested in implementation version 201310111528.  The following plugin is affected:       Laravel4 Framework 
Some plugins require plugin PHP Framework API to be installed.
The plugin PHP Framework API is requested in implementation version 201310111528.  The following plugin is affected:       Laravel4 Framework 
Some plugins require plugin PHP Module API to be installed.
The plugin PHP Module API is requested in implementation version 201310111528.  The following plugin is affected:       Laravel4 Framework 
Some plugins require plugin Composer to be installed.
The plugin Composer is requested in implementation version 201312091611.  The following plugin is affected:       Laravel4 Framework  Some plugins not installed to avoid potential installation problems.
