### ISSUE TITLE
how can i use laravel?

### ISSUE THREAD

**Issue by mohammad6006** [nbphpcouncil/nb-laravel-plugin#6]
i install this plugin in 7.4 nb

but i dont know how can i use that?

i can not found laravel in new project or new files

**Comment by junichi11** [comment]
Did you set zip file to Options?
`Tools > Options > PHP > Laravel4`

**Comment by mohammad6006** [comment]
yes i do that and set laravel.zip file path

so what i do after that?

**Comment by junichi11** [comment]
You can create new laravel project. New Project > PHP > .... > Frameworks
Probably, a file for auto completion is also created.

**Comment by mohammad6006** [comment]
in php just there are 
php aplication
with remote server
existing source

not find anything like laravel

**Comment by junichi11** [comment]
It's right.
PHP Application > ... next ...> Frameworks (Step1 -> 2 -> 3 -> 4)
You can find Framework list there.

**Comment by mohammad6006** [comment]
thank you 

i find it

but now i have one problem

when resolve show this error 

invalid include path 
Path C:\wamp\www\lara\nbproject\autocomplete is already part of project.

**Comment by junichi11** [comment]
@mohammad6006 
Probably, that error is not a big problem.

@jtakakura Could you fix this problem?
